backend:
  name: git-gateway
  branch: main

media_folder: "main/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "main/content/home.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: "Description", name: "description", widget: "text" }
